# Generated by Django 2.0.3 on 2018-03-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elementos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Elemento', models.CharField(max_length=35)),
                ('Simbolo_Elemento', models.CharField(max_length=35)),
                ('Informacion_Elemento', models.CharField(max_length=200)),
                ('Foto_Elemento', models.CharField(max_length=50)),
                ('Foto_Tarjeta', models.CharField(max_length=50)),
            ],
        ),
    ]
