# Generated by Django 2.0.3 on 2018-04-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alchemy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mezclas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Mezcla', models.CharField(max_length=35)),
                ('Elemento1', models.CharField(max_length=35)),
                ('Elemento2', models.CharField(max_length=35)),
                ('Foto_Mezcla', models.CharField(max_length=35)),
            ],
        ),
    ]
